package com.utcn.userservice.dto.builders;

import com.utcn.userservice.dto.UserDTO;
import com.utcn.userservice.model.User;

public class UserBuilder {
    public static UserDTO toUserDTO(User user) {
        return new UserDTO(user.getId(), user.getUsername(), user.getAge(), user.getTown(), user.getRegisterDate());
    }

    public static User toEntity(UserDTO userDTO) {
        // Omit the ID here as it's generated by the DB on INSERT
        return new User(userDTO.username(), "placeholder_password", userDTO.age(), userDTO.town());
    }
}